import type { HostSkillRegistration } from './contract.ts'

/** User-invoked `/codegraph` skill registered beside `codegraph_explore`. */
export const CODEGRAPH_SKILL: HostSkillRegistration = {
  name: 'codegraph',
  description: "Warm this project root's index snapshot, then run a diff impact pass on uncommitted changes.",
  source: 'runtime',
  invocation: { modelInvocable: true, userInvocable: true },
  content: [
    "Warm this project root's index snapshot, then run a diff impact pass only if the working tree is dirty.",
    '',
    '## Plugin must be on',
    '',
    'If `codegraph_explore` is missing from this turn\'s tools, stop and tell the user the CodeGraph plugin is not on.',
    '',
    '## 1. Index warmup',
    '',
    'Call `codegraph_explore` with structured `mode` and `target`. The `query` field only supplements those fields.',
    '',
    'Use an existing mode (`callers`, `impact`, or `reachability`). Repeat until `metadata.index.status` is `built`, `reused`, `rebuilt`, or `incremental`.',
    '',
    '- Dirty tree: `mode: callers` with a `target` from the uncommitted diff in the session cwd.',
    '- Clean tree: `mode: callers` with any structured `target` from this project root — the index still builds.',
    '',
    'Done when status is not `indexing`. If status is `indexing`, stop before the diff impact pass and tell the user to retry.',
    '',
    'Paths in the result are this session\'s project root only. Leave the index snapshot to `codegraph_explore`.',
    '',
    '## 2. Diff impact pass',
    '',
    'After successful warmup, inspect the session cwd (`git diff` plus untracked source files).',
    '',
    '- Clean working tree: skip the diff impact pass. Warmup is the whole run.',
    '- Dirty working tree: at most 10 top-level exported symbols from the uncommitted diff.',
    '  - Prefer `impact` for what the change touches; `callers` when the symbol is a function being edited.',
    '  - No recognizable top-level exports: set `scope` to that file\'s path prefix.',
    '  - Symbols past 10: truncated — note it, then stop adding targets.',
    '',
    'On every edge, report `confidence`. Treat `heuristic` as a guess. If `candidates` appear, stop and disambiguate.',
  ].join('\n'),
}
